services:
  api:
    build:
      context: "."
      dockerfile: "./API/Dockerfile"
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - EMAIL_CONFIRMATION_ENDPOINT=http://localhost/api/auth/confirm-email
      - EMAIL_CHANGE_CONFIRMATION_ENDPOINT=http://localhost/api/auth/confirm-email-change
    depends_on:
      - database
      - minio
  
  subscription-service:
    build:
      context: "./SubscriptionService/subscription-service"
      dockerfile: "./Dockerfile"
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - JWT_KEY=000011112222333344445555666677778888
        
  database:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - ~/postgres/Netflix:/var/lib/postgresql/data
  
  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data
    volumes:
      - '~/minio/data:/data'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=aboba228

  frontend:
    build:
      context: "./Frontend"
      dockerfile: "./Dockerfile"
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./Frontend/
        target: /app
    tty: true
    environment:
      - VITE_PORT=5173
      - VITE_HOST=0.0.0.0
#      - VITE_CLIENT_PORT=5173
    depends_on:
      - api
      - subscription-service
    
  proxy:
    image: nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/localhost.crt:/etc/nginx/localhost.crt
      - ./Nginx/localhost.key:/etc/nginx/localhost.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - api
      - subscription-service