// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommentUser", b =>
                {
                    b.Property<long>("ScoredByUsersId")
                        .HasColumnType("bigint")
                        .HasColumnName("scored_by_users_id");

                    b.Property<long>("ScoredCommentsId")
                        .HasColumnType("bigint")
                        .HasColumnName("scored_comments_id");

                    b.HasKey("ScoredByUsersId", "ScoredCommentsId")
                        .HasName("pk_comment_user");

                    b.HasIndex("ScoredCommentsId")
                        .HasDatabaseName("ix_comment_user_scored_comments_id");

                    b.ToTable("comment_user", (string)null);
                });

            modelBuilder.Entity("ContentBaseSubscription", b =>
                {
                    b.Property<long>("AccessibleContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("accessible_content_id");

                    b.Property<int>("AllowedSubscriptionsId")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_subscriptions_id");

                    b.HasKey("AccessibleContentId", "AllowedSubscriptionsId")
                        .HasName("pk_content_base_subscription");

                    b.HasIndex("AllowedSubscriptionsId")
                        .HasDatabaseName("ix_content_base_subscription_allowed_subscriptions_id");

                    b.ToTable("content_base_subscription", (string)null);
                });

            modelBuilder.Entity("Domain.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("WrittenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("written_at");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("ix_comments_review_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Domain.ContentBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("content_type_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("poster_url");

                    b.Property<string>("Slogan")
                        .HasColumnType("text")
                        .HasColumnName("slogan");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId")
                        .HasDatabaseName("ix_content_bases_content_type_id");

                    b.ToTable("content_bases", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.ContentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type_name");

                    b.HasKey("Id")
                        .HasName("pk_content_types");

                    b.HasIndex("ContentTypeName")
                        .IsUnique()
                        .HasDatabaseName("ix_content_types_content_type_name");

                    b.ToTable("content_types", (string)null);
                });

            modelBuilder.Entity("Domain.Episode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<int>("SeasonInfoId")
                        .HasColumnType("integer")
                        .HasColumnName("season_info_id");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("pk_episode");

                    b.HasIndex("SeasonInfoId")
                        .HasDatabaseName("ix_episode_season_info_id");

                    b.ToTable("episode", (string)null);
                });

            modelBuilder.Entity("Domain.FavouriteContent", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("UserId", "ContentId")
                        .HasName("pk_favourite_contents");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ix_favourite_contents_content_id");

                    b.ToTable("favourite_contents", (string)null);
                });

            modelBuilder.Entity("Domain.Genre", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ContentsId")
                        .HasColumnType("bigint")
                        .HasColumnName("contents_id");

                    b.Property<string>("GenresName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("genres_name");

                    b.HasKey("Name")
                        .HasName("pk_genres");

                    b.HasIndex("ContentsId")
                        .HasDatabaseName("ix_genres_contents_id");

                    b.HasIndex("GenresName")
                        .HasDatabaseName("ix_genres_genres_name");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("Domain.PersonInContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("integer")
                        .HasColumnName("profession_id");

                    b.HasKey("Id")
                        .HasName("pk_person_in_contents");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ix_person_in_contents_content_id");

                    b.HasIndex("ProfessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_in_contents_profession_id");

                    b.ToTable("person_in_contents", (string)null);
                });

            modelBuilder.Entity("Domain.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProfessionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profession_name");

                    b.HasKey("Id")
                        .HasName("pk_professions");

                    b.ToTable("professions", (string)null);
                });

            modelBuilder.Entity("Domain.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_id");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_positive");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("WrittenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("written_at");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ix_reviews_content_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("Domain.SeasonInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<long>("SerialContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("serial_content_id");

                    b.HasKey("Id")
                        .HasName("pk_season_infos");

                    b.HasIndex("SerialContentId")
                        .HasDatabaseName("ix_season_infos_serial_content_id");

                    b.ToTable("season_infos", (string)null);
                });

            modelBuilder.Entity("Domain.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("BoughtAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bought_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("BirthDay")
                        .HasColumnType("date")
                        .HasColumnName("birth_day");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.UsersReviews", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_liked");

                    b.HasKey("UserId", "ReviewId")
                        .HasName("pk_users_reviews");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("ix_users_reviews_review_id");

                    b.ToTable("users_reviews", (string)null);
                });

            modelBuilder.Entity("Domain.MovieContent", b =>
                {
                    b.HasBaseType("Domain.ContentBase");

                    b.Property<long>("MovieLength")
                        .HasColumnType("bigint")
                        .HasColumnName("movie_length");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("video_url");

                    b.ToTable("movie_contents", (string)null);
                });

            modelBuilder.Entity("Domain.SerialContent", b =>
                {
                    b.HasBaseType("Domain.ContentBase");

                    b.ToTable("serial_contents", (string)null);
                });

            modelBuilder.Entity("CommentUser", b =>
                {
                    b.HasOne("Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ScoredByUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_user_users_scored_by_users_id");

                    b.HasOne("Domain.Comment", null)
                        .WithMany()
                        .HasForeignKey("ScoredCommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_user_comments_scored_comments_id");
                });

            modelBuilder.Entity("ContentBaseSubscription", b =>
                {
                    b.HasOne("Domain.ContentBase", null)
                        .WithMany()
                        .HasForeignKey("AccessibleContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_base_subscription_content_bases_accessible_content_");

                    b.HasOne("Domain.Subscription", null)
                        .WithMany()
                        .HasForeignKey("AllowedSubscriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_base_subscription_subscriptions_allowed_subscriptio");
                });

            modelBuilder.Entity("Domain.Comment", b =>
                {
                    b.HasOne("Domain.Review", "Review")
                        .WithMany("Comments")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_reviews_review_id");

                    b.HasOne("Domain.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.ContentBase", b =>
                {
                    b.HasOne("Domain.ContentType", "ContentType")
                        .WithMany("ContentsWithType")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_bases_content_types_content_type_id");

                    b.OwnsOne("Domain.AgeRatings", "AgeRatings", b1 =>
                        {
                            b1.Property<long>("ContentBaseId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<int>("Age")
                                .HasColumnType("integer")
                                .HasColumnName("age_ratings_age");

                            b1.Property<string>("AgeMpaa")
                                .HasColumnType("text")
                                .HasColumnName("age_ratings_age_mpaa");

                            b1.HasKey("ContentBaseId");

                            b1.ToTable("content_bases");

                            b1.WithOwner()
                                .HasForeignKey("ContentBaseId")
                                .HasConstraintName("fk_content_bases_content_bases_id");
                        });

                    b.OwnsOne("Domain.Budget", "Budget", b1 =>
                        {
                            b1.Property<long>("ContentBaseId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("BudgetCurrencyName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("budget_budget_currency_name");

                            b1.Property<int>("BudgetValue")
                                .HasColumnType("integer")
                                .HasColumnName("budget_budget_value");

                            b1.HasKey("ContentBaseId");

                            b1.ToTable("content_bases");

                            b1.WithOwner()
                                .HasForeignKey("ContentBaseId")
                                .HasConstraintName("fk_content_bases_content_bases_id");
                        });

                    b.OwnsOne("Domain.Ratings", "Ratings", b1 =>
                        {
                            b1.Property<long>("ContentBaseId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<float?>("ImdbRating")
                                .HasColumnType("real")
                                .HasColumnName("ratings_imdb_rating");

                            b1.Property<float?>("KinopoiskRating")
                                .HasColumnType("real")
                                .HasColumnName("ratings_kinopoisk_rating");

                            b1.Property<float?>("LocalRating")
                                .HasColumnType("real")
                                .HasColumnName("ratings_local_rating");

                            b1.HasKey("ContentBaseId");

                            b1.ToTable("content_bases");

                            b1.WithOwner()
                                .HasForeignKey("ContentBaseId")
                                .HasConstraintName("fk_content_bases_content_bases_id");
                        });

                    b.OwnsOne("Domain.TrailerInfo", "TrailerInfo", b1 =>
                        {
                            b1.Property<long>("ContentBaseId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("trailer_info_name");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("trailer_info_url");

                            b1.HasKey("ContentBaseId");

                            b1.ToTable("content_bases");

                            b1.WithOwner()
                                .HasForeignKey("ContentBaseId")
                                .HasConstraintName("fk_content_bases_content_bases_id");
                        });

                    b.Navigation("AgeRatings");

                    b.Navigation("Budget");

                    b.Navigation("ContentType");

                    b.Navigation("Ratings");

                    b.Navigation("TrailerInfo");
                });

            modelBuilder.Entity("Domain.Episode", b =>
                {
                    b.HasOne("Domain.SeasonInfo", "SeasonInfo")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episode_season_infos_season_info_id");

                    b.Navigation("SeasonInfo");
                });

            modelBuilder.Entity("Domain.FavouriteContent", b =>
                {
                    b.HasOne("Domain.ContentBase", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favourite_contents_content_bases_content_id");

                    b.HasOne("Domain.User", "User")
                        .WithMany("FavouriteContents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favourite_contents_users_user_id");

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Genre", b =>
                {
                    b.HasOne("Domain.ContentBase", null)
                        .WithMany()
                        .HasForeignKey("ContentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_genres_content_bases_contents_id");

                    b.HasOne("Domain.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_genres_genres_genres_name");
                });

            modelBuilder.Entity("Domain.PersonInContent", b =>
                {
                    b.HasOne("Domain.ContentBase", "Content")
                        .WithMany("PersonsInContent")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_in_contents_content_bases_content_id");

                    b.HasOne("Domain.Profession", "Profession")
                        .WithOne()
                        .HasForeignKey("Domain.PersonInContent", "ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_in_contents_professions_profession_id");

                    b.Navigation("Content");

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("Domain.Review", b =>
                {
                    b.HasOne("Domain.ContentBase", "Content")
                        .WithMany("Reviews")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_content_bases_content_id");

                    b.HasOne("Domain.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_user_id");

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.SeasonInfo", b =>
                {
                    b.HasOne("Domain.SerialContent", "SerialContent")
                        .WithMany("SeasonInfos")
                        .HasForeignKey("SerialContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_season_infos_serial_contents_serial_content_id");

                    b.Navigation("SerialContent");
                });

            modelBuilder.Entity("Domain.UsersReviews", b =>
                {
                    b.HasOne("Domain.Review", "Review")
                        .WithMany("RatedByUsers")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_reviews_reviews_review_id");

                    b.HasOne("Domain.User", "User")
                        .WithMany("ScoredReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_reviews_users_user_id");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.MovieContent", b =>
                {
                    b.HasOne("Domain.ContentBase", null)
                        .WithOne()
                        .HasForeignKey("Domain.MovieContent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_contents_content_bases_id");
                });

            modelBuilder.Entity("Domain.SerialContent", b =>
                {
                    b.HasOne("Domain.ContentBase", null)
                        .WithOne()
                        .HasForeignKey("Domain.SerialContent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_serial_contents_content_bases_id");

                    b.OwnsOne("Domain.YearRange", "YearRange", b1 =>
                        {
                            b1.Property<long>("SerialContentId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date")
                                .HasColumnName("year_range_end");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date")
                                .HasColumnName("year_range_start");

                            b1.HasKey("SerialContentId");

                            b1.ToTable("serial_contents");

                            b1.WithOwner()
                                .HasForeignKey("SerialContentId")
                                .HasConstraintName("fk_serial_contents_serial_contents_id");
                        });

                    b.Navigation("YearRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.ContentBase", b =>
                {
                    b.Navigation("PersonsInContent");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.ContentType", b =>
                {
                    b.Navigation("ContentsWithType");
                });

            modelBuilder.Entity("Domain.Review", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RatedByUsers");
                });

            modelBuilder.Entity("Domain.SeasonInfo", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FavouriteContents");

                    b.Navigation("Reviews");

                    b.Navigation("ScoredReviews");
                });

            modelBuilder.Entity("Domain.SerialContent", b =>
                {
                    b.Navigation("SeasonInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
