name: netflix
description: "Netflix"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  go_router: ^15.1.1
  equatable: ^2.0.7
  collection: ^1.19.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  youtube_player_iframe: ^5.2.1
  graphql_flutter: ^5.2.0
  flutter_dotenv: ^5.2.1
  dio_cookie_manager: ^3.2.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env.template
