apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Release
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: AllowedHosts
              value: '*'
            - name: Database__ConnectionString
              value: User ID=postgres;Password=admin;Host=database;Port=5432;Database=Netflix;Pooling=true;
            - name: Database__Identity
              value: User ID=postgres;Password=admin;Host=database;Port=5432;Database=Netflix.Identity;Pooling=true;
            - name: EMAIL_CHANGE_CONFIRMATION_ENDPOINT
              value: https://localhost/api/auth/confirm-email-change
            - name: EMAIL_CONFIRMATION_ENDPOINT
              value: https://localhost/api/auth/confirm-email
            - name: EmailOptions__From
              value: someemail@gmail.com
            - name: EmailOptions__Password
              value: aaaa bbbb cccc dddd
            - name: EmailOptions__Port
              value: "587"
            - name: EmailOptions__SmtpServer
              value: smtp.gmail.com
            - name: EmailOptions__Username
              value: someemail@gmail.com
            - name: FrontendConfig__Url
              value: https://localhost:443
            - name: HLS_BASE_URL
              value: https://localhost/api
            - name: JwtOptions__AccessTokenLifetimeInMinutes
              value: "150000000"
            - name: JwtOptions__Key
              value: 23ec772b436632ee93e30373ebc1817b355bdfd1356fd677d993b2f90923bb816e55bbf53d6a74fea0c38d1beaf0bbce87a2d8dddcaa629dbc75284e64a27697a17d7f537a6d45d2138ba25c187a3306e376a7f85ee78c91a5d35cbf0e986d66514bd11641dfe57c704312ddf4262293f092e8b7c2aad412263afacab3550cebd1c78dae487ced46596647deee24ff9689f8244df3928198f97f44f5117734db47eac0d243814a11c43a3214a225368a8be0ad5cbb52d4c3fffaec009f5ec84b592ff338d71cd74f658f654df2e388dd79fbb2a17efd3367fdfcf3da2a60b2c4038d0e746f57b29597a5cf0716ffc5f53dbecd3c11e6ea0cba4d3218dd292ea1
            - name: JwtOptions__RefreshTokenLifetimeInDays
              value: "30"
            - name: Minio__AccessKey
              value: DFGDSFG12321FSDFADSFSADG4324234JGHJGHJ876123
            - name: Minio__Endpoint
              value: minio:9000
            - name: Minio__ExternalEndpoint
              value: minio
            - name: Minio__Port
              value: "9000"
            - name: Minio__SecretKey
              value: QWEQWEQWE312256870BBXVVHCF87888DFGCR345345123
            - name: Redis__Host
              value: redis
            - name: Redis__Password
              value: lolkekcheburek
            - name: Redis__Port
              value: "6379"
          image: api
          name: api
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
