apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: support-persistent-service
  name: support-persistent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: support-persistent-service
  template:
    metadata:
      labels:
        io.kompose.service: support-persistent-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Release
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: Database__ConnectionString
              value: User ID=postgres;Password=admin;Host=database;Port=5432;Database=Netflix.Support;Pooling=true;
            - name: FrontendConfig__Url
              value: https://localhost:443
            - name: JwtOptions__Key
              value: 23ec772b436632ee93e30373ebc1817b355bdfd1356fd677d993b2f90923bb816e55bbf53d6a74fea0c38d1beaf0bbce87a2d8dddcaa629dbc75284e64a27697a17d7f537a6d45d2138ba25c187a3306e376a7f85ee78c91a5d35cbf0e986d66514bd11641dfe57c704312ddf4262293f092e8b7c2aad412263afacab3550cebd1c78dae487ced46596647deee24ff9689f8244df3928198f97f44f5117734db47eac0d243814a11c43a3214a225368a8be0ad5cbb52d4c3fffaec009f5ec84b592ff338d71cd74f658f654df2e388dd79fbb2a17efd3367fdfcf3da2a60b2c4038d0e746f57b29597a5cf0716ffc5f53dbecd3c11e6ea0cba4d3218dd292ea1
            - name: RabbitMqConfig__Hostname
              value: amqp://rabbitmq:5672
            - name: RabbitMqConfig__Password
              value: admin123
            - name: RabbitMqConfig__Username
              value: admin
          image: support-persistent-service
          name: support-persistent-service
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
