apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: support-persistent-service
  name: support-persistent-service
spec:
  ports:
    - name: "10000"
      port: 10000
      targetPort: 8080
    - name: "10001"
      port: 10001
      targetPort: 8081
  selector:
    io.kompose.service: support-persistent-service
