name: BackAnalyze

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  inspection:
    
    runs-on: ubuntu-latest
    
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore Netflix.sln
      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: Netflix.sln
          dotnetVersion: ${{ steps.setup-dotnet.outputs.dotnet-version }}
          minimumSeverity: WARNING
          minimumReportSeverity: WARNING