name: netflix_app

on: 
    push:
        branches:
            - "main"
jobs:
    build:
        name: Deploy new code
        runs-on: ubuntu-latest 
        steps:   
            - name: Set up SSH connection
              uses: webfactory/ssh-agent@v0.5.3
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Connect to remote server and deploy
              run: |
                ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SSH_SERVER }} << EOF
                  cd app
                  docker-compose down
                  git pull
                  docker-compose up -d
                EOF
              
