name: React

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-front:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: Frontend/package-lock.json
          node-version: "latest"
          cache: "npm"
      - run: npm ci
        working-directory: Frontend
      - run: npm run build
        working-directory: Frontend
      - run: npx vitest
        working-directory: Frontend
        